version: '3.4'

networks:
  overlay:

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  nginx_letsencrypt:
    driver: local
  backend_logs:
    driver: local
  grafana_data:
    driver: local

services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: urbanlabs-nginx
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=binakot@gmail.com
    ports:
      - 80:80
      - 443:443
    networks:
      - overlay
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/user_conf.d/urbanlabs.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - nginx_letsencrypt:/etc/letsencrypt

  landing:
    image: urbanlabs-landing:latest
    container_name: urbanlabs-landing
    restart: unless-stopped
    networks:
      - overlay

  client:
    image: urbanlabs-client:latest
    container_name: urbanlabs-client
    restart: unless-stopped
    networks:
      - overlay

  admin:
    image: urbanlabs-admin:latest
    container_name: urbanlabs-admin
    restart: unless-stopped
    networks:
      - overlay

  rabbitmq:
    image: rabbitmq:3-management
    container_name: urbanlabs-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    networks:
      - overlay

  backend:
    image: urbanlabs-backend:latest
    container_name: urbanlabs-backend
    restart: unless-stopped
    environment:
      - JAVA_OPTIONS=-Xmx512m -Xmx4g
      - SPRING_DATASOURCE_URL=jdbc:postgresql://urbanlabs-postgresql:5432/postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - overlay
    volumes:
      - backend_logs:/logs

  postgres:
    image: timescale/timescaledb-postgis:2.3.0-pg12
    container_name: urbanlabs-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - overlay
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: urbanlabs-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=urbanlabs@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=urbanlabs
    ports:
      - 5433:80
    networks:
      - overlay
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: urbanlabs-swagger
    restart: unless-stopped
    environment:
      - URL=https://api.urbanlabs.ru/v2/api-docs
      - OAUTH_CLIENT_ID=web
      - OAUTH_CLIENT_SECRET=secret
      - OAUTH_APP_NAME=urbanlabs
      - OAUTH_SCOPES=all
    networks:
      - overlay

  grafana:
    image: grafana/grafana:latest
    container_name: urbanlabs-grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - overlay
    volumes:
      - grafana_data:/var/lib/grafana
