{
 "title": "plot",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Общее потребление электроэнергии",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fix_time, watt\n\tFROM public.power_socket_telemetry"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Текущее потребление электроэнергии",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fix_time, 42123 as value\n\tFROM public.power_socket_telemetry;"
    }
   ]
  },
  {
   "title": "Общее потребление воды",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mlitre" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT water_volume\n\tFROM public.water_socket_telemetry\n\torder by fix_time desc\n\tlimit 1;"
    }
   ]
  },
  {
   "title": "Температура",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 1\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 1"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 2\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 2"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 3\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 3"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 4\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 4"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 5\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 5"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 6\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 6"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 7\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 7"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 8\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 8"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 9\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 9"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 10\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 10"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 11\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 11"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 12\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 12"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 13\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 13"
    },
    {
     "rawSql": "SELECT fix_time, temp/27 as \"Помещение 14\"\n\tFROM public.temp_socket_telemetry\n\twhere equipment_id = 14"
    }
   ]
  }
 ]
}